/*
 * DynViz.java
 *
 * Created on Nov 6, 2010, 8:50:30 PM
 */

import java.awt.Graphics;

/**
 *
 * @author gmcwhirt
 */
public class DynViz extends javax.swing.JApplet {

    /** Initializes the applet DynViz */
    @Override
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                @Override
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BRGraphPanel = new DrawingPanel();
        DtRGraphPanel = new DrawingPanel();
        CtRGraphPanel = new DrawingPanel();

        setName("DynVizApplet"); // NOI18N
        setStub(null);

        BRGraphPanel.setBackground(new java.awt.Color(255, 255, 255));
        BRGraphPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BRGraphPanel.setForeground(new java.awt.Color(0, 0, 0));
        BRGraphPanel.setToolTipText("Best Response Dynamics");
        BRGraphPanel.setFocusable(false);
        BRGraphPanel.setMaximumSize(new java.awt.Dimension(200, 200));
        BRGraphPanel.setMinimumSize(new java.awt.Dimension(200, 200));
        BRGraphPanel.setName("BRGraphPanel"); // NOI18N
        BRGraphPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        BRGraphPanel.setRequestFocusEnabled(false);
        BRGraphPanel.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout BRGraphPanelLayout = new javax.swing.GroupLayout(BRGraphPanel);
        BRGraphPanel.setLayout(BRGraphPanelLayout);
        BRGraphPanelLayout.setHorizontalGroup(
            BRGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        BRGraphPanelLayout.setVerticalGroup(
            BRGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        DtRGraphPanel.setBackground(new java.awt.Color(255, 255, 255));
        DtRGraphPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DtRGraphPanel.setForeground(new java.awt.Color(0, 0, 0));
        DtRGraphPanel.setToolTipText("Best Response Dynamics");
        DtRGraphPanel.setDoubleBuffered(false);
        DtRGraphPanel.setFocusable(false);
        DtRGraphPanel.setMaximumSize(new java.awt.Dimension(200, 200));
        DtRGraphPanel.setMinimumSize(new java.awt.Dimension(200, 200));
        DtRGraphPanel.setName("BRGraphPanel"); // NOI18N
        DtRGraphPanel.setRequestFocusEnabled(false);
        DtRGraphPanel.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout DtRGraphPanelLayout = new javax.swing.GroupLayout(DtRGraphPanel);
        DtRGraphPanel.setLayout(DtRGraphPanelLayout);
        DtRGraphPanelLayout.setHorizontalGroup(
            DtRGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        DtRGraphPanelLayout.setVerticalGroup(
            DtRGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        CtRGraphPanel.setBackground(new java.awt.Color(255, 255, 255));
        CtRGraphPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CtRGraphPanel.setForeground(new java.awt.Color(0, 0, 0));
        CtRGraphPanel.setToolTipText("Best Response Dynamics");
        CtRGraphPanel.setDoubleBuffered(false);
        CtRGraphPanel.setFocusable(false);
        CtRGraphPanel.setMaximumSize(new java.awt.Dimension(200, 200));
        CtRGraphPanel.setMinimumSize(new java.awt.Dimension(200, 200));
        CtRGraphPanel.setName("BRGraphPanel"); // NOI18N
        CtRGraphPanel.setRequestFocusEnabled(false);
        CtRGraphPanel.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout CtRGraphPanelLayout = new javax.swing.GroupLayout(CtRGraphPanel);
        CtRGraphPanel.setLayout(CtRGraphPanelLayout);
        CtRGraphPanelLayout.setHorizontalGroup(
            CtRGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        CtRGraphPanelLayout.setVerticalGroup(
            CtRGraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BRGraphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DtRGraphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(CtRGraphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BRGraphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DtRGraphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CtRGraphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DrawingPanel BRGraphPanel;
    private DrawingPanel CtRGraphPanel;
    private DrawingPanel DtRGraphPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void paint(Graphics g) {
        //drawGraph();
        BRGraphPanel.setVisible(true);
        DtRGraphPanel.setVisible(true);
        CtRGraphPanel.setVisible(true);
    }

    protected void drawGraph() {
        BRGraphPanel.demoText("test");
        BRGraphPanel.repaint();
    }
}
